### ISSUE TITLE
Usable as loadable extension?

### ISSUE THREAD

**Issue by mindreframer** [aergoio/sqlite-stored-procedures#1]
Hey @kroggen,

would it be possible to package this library as loadable extension? Or are there any major objections to this? 

Cheers, 
Roman

**Comment by kroggen** [comment]
As far as I know, it is not possible to package this into a loadable extension because they do not support new SQL commands and there are internal modifications on SQLite to allow this feature

**Comment by mindreframer** [comment]
@kroggen Thank you for the quick response! 
OK, this is what I have suspected... That's a shame, it would be so great! 

Have a good day!
